version: '3'

services:
  frontend:
    image: node:8
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: >
      bash -c "cd /app &&
               npm install && 
               npm rebuild node-sass &&
               npm run watch"
